# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        admin:
             memory:
                   users:
                        admin: { password: secret, roles: [ 'ROLE_ADMIN' ] }
        aimeos_customer:
             entity: { class: AimeosShopBundle:User, property: username }
        in_memory:
            memory: ~

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            Aimeos\ShopBundle\Entity\User:
                algorithm: sha1
                encode_as_base64: false
                iterations: 1

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        aimeos_admin:
                    pattern:   ^/(admin|extadm|jqadm|jsonadm)
                    anonymous: ~
                    provider: admin
                    form_login:
                        login_path: /admin
                        check_path: /admin_check
        aimeos_myaccount:
                    pattern: ^/myaccount
                    provider: aimeos_customer
                    http_basic:
                        realm: "MyAccount"
        main:
                    anonymous: ~

    access_control:
            - { path: ^/(extadm|jqadm|jsonadm), roles: ROLE_ADMIN }
            - { path: ^/myaccount, roles: ROLE_USER }



      #  main:
       #     anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
